poses:
- position:
    x: -2.40
    y: 0.66
    z: 1.27
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: -0.23
    y: 2.206
    z: 1.27
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 3.17
    y: 2.83
    z: 1.687
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 3.199
    y: -0.61
    z: 1.829
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 2.39
    y: -2.708
    z: 1.722
  orientation:
    x: 0
    y: 0
    z: 0
    w: 1.0
- position:
    x: -0.11
    y: -2.81
    z: 1.27
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: -2.52
    y: -2.309
    z: 1.23
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0