poses:
- position:
    x: -2.81
    y: 2.89
    z: 1.50
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 0.06
    y: 2.47
    z: 1.19
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 2.87 
    y: 2.63
    z: 1.68
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 3.46
    y: 0.16
    z: 2.54
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 2.95
    y: -2.66
    z: 1.62
  orientation:
    x: 0
    y: 0
    z: 0
    w: 1.0
- position:
    x: -0.09
    y: -2.20
    z: 1.24
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: -2.96
    y: -2.90
    z: 1.58
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0